builds:
  - id: obs
    binary: obs
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: obs
    homepage: https://github.com/joelvaneenwyk/obsidian-cli
    tap:
      owner: joelvaneenwyk
      name: homebrew-joelvaneenwyk
    commit_author:
      name: joelvaneenwyk
      email: joelvaneenwyk@gmail.com

scoops:
  - name: obs
    homepage: https://github.com/joelvaneenwyk/obsidian-cli
    bucket:
      owner: joelvaneenwyk
      name: scoop-joelvaneenwyk
    commit_author:
      name: joelvaneenwyk
      email: joelvaneenwyk@gmail.com

aurs:
  - name: obs-bin
    homepage: https://github.com/joelvaneenwyk/obsidian-cli
    description: Interact with Obsidian in the terminal. Open, search, create, update and move notes!
    maintainers:
      - 'Joel Van Eenwyk <joelvaneenwyk at gmail dot com>'
      - 'Kartikay Jainwal <kartikayjainwal at gmail dot com>'
      - 'Jonathan Neidel <aur at jneidel dot com>'
    license: 'MIT'
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/obs-bin.git'
    package: |-
      install -Dm755 "./obs" "${pkgdir}/usr/bin/obs"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"

checksum:
  name_template: "checksums.txt"
